openai:
  model: gpt-4o
  temperature: 0.7

hallucination:
  method: embedding  # options: llm_judge, embedding, vectara

metadata:
  use_case: technical explanation
  ground_truth_type: text

embedding:
  model: text-embedding-3-small
  provider: openai   # future: sbert, etc.
